export const PRICING = {
  MIN_FIXED_CENTS: 9_900,
  MAX_FIXED_CENTS: 100_000,

  MAX_VARIABLE_BPS: 2_000,
  MIN_VARIABLE_BPS: 700,

  CONTRACTOR_SHARE_OF_FIXED_BPS: 4_000,
  CONTRACTOR_SHARE_OF_VARIABLE_BPS: 2_000,

  PLAN_CHANGE_COOLDOWN_DAYS: 30,
} as const;

export const PRICING_FIXED_RANGE_CENTS =
  PRICING.MAX_FIXED_CENTS - PRICING.MIN_FIXED_CENTS;
export const PRICING_VARIABLE_RANGE_BPS =
  PRICING.MAX_VARIABLE_BPS - PRICING.MIN_VARIABLE_BPS;

export const CURRENCY = 'USD' as const;
